# -*- coding: utf-8 -*-
"""antakyatiler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6WhHUk8UI2iWBEBh7_WSlpVk7qdpTPx
"""

# STEP 1: Install required packages
!pip install rasterio shapely pyproj tqdm --quiet

# STEP 2: Imports
import os
import json
import numpy as np
import rasterio
from shapely.geometry import shape, box
from shapely.ops import transform
from rasterio.features import rasterize
from pyproj import Transformer
from tqdm import tqdm
import matplotlib.pyplot as plt
import shutil

# STEP 3: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# STEP 4: Define paths
BASE_DIR = "/content/drive/MyDrive/thesis/data"
PRE_PATH = os.path.join(BASE_DIR, "PREFF95000.tif")
POST_PATH = os.path.join(BASE_DIR, "POSTCB600.tif")
LABEL_PATH = os.path.join(BASE_DIR, "hotosm_tur_destroyed_buildings_polygons_geojson.geojson")
OUT_DIR = os.path.join(BASE_DIR, "output")
ZIP_PATH = os.path.join(BASE_DIR, "tiles_output.zip")

# Tiling config
PATCH_SIZE = 256
STRIDE = 224

# Ensure clean output directory
if os.path.exists(OUT_DIR):
    shutil.rmtree(OUT_DIR)
os.makedirs(OUT_DIR, exist_ok=True)

# Ensure old zip is removed
if os.path.exists(ZIP_PATH):
    os.remove(ZIP_PATH)

# STEP 5: Helper functions
def normalize_img(img):
    return img / 255.0

def load_reprojected_polygons(geojson_path, raster_path):
    with open(geojson_path, 'r') as f:
        gj = json.load(f)

    with rasterio.open(raster_path) as src:
        bounds = src.bounds
        raster_bbox = box(*bounds)
        raster_crs = src.crs

    transformer = Transformer.from_crs("EPSG:4326", raster_crs, always_xy=True)

    polygons = []
    for feature in gj['features']:
        try:
            geom = shape(feature['geometry'])
            reprojected_geom = transform(transformer.transform, geom)
            if reprojected_geom.intersects(raster_bbox):
                cropped = reprojected_geom.intersection(raster_bbox)
                if not cropped.is_empty:
                    polygons.append(cropped)
        except Exception as e:
            print(f"  [Warning] Geometry parse failed: {e}")

    print(f"→ Loaded {len(polygons)} reprojected polygons intersecting raster")
    return polygons

def rasterize_collapse_mask(polygons, ref_path):
    with rasterio.open(ref_path) as src:
        out_shape = (src.height, src.width)
        transform = src.transform

    mask = rasterize(
        [(poly, 1) for poly in polygons],
        out_shape=out_shape,
        transform=transform,
        fill=0,
        dtype=np.uint8
    ) if polygons else np.zeros(out_shape, dtype=np.uint8)

    print("✅ Mask unique values (should include 1 if buildings exist):", np.unique(mask))

    # Optional: visualize the full rasterized mask
    plt.figure(figsize=(10, 5))
    plt.imshow(mask, cmap='gray')
    plt.title("Rasterized Damage Mask (Full Scene)")
    plt.axis('off')
    plt.show()

    return mask

def tile_and_save(img_6ch, mask, out_dir):
    _, H, W = img_6ch.shape
    tile_count = 0
    damaged_tiles = []

    for y in tqdm(range(0, H - PATCH_SIZE + 1, STRIDE), desc="Tiling rows"):
        for x in range(0, W - PATCH_SIZE + 1, STRIDE):
            img_tile = img_6ch[:, y:y+PATCH_SIZE, x:x+PATCH_SIZE]
            mask_tile = mask[y:y+PATCH_SIZE, x:x+PATCH_SIZE]

            # Save files
            np.save(os.path.join(out_dir, f"img_{tile_count:06d}.npy"), img_tile.astype(np.float32))
            np.save(os.path.join(out_dir, f"mask_{tile_count:06d}.npy"), mask_tile.astype(np.uint8))

            # Track damaged tiles
            if np.any(mask_tile):
                damaged_tiles.append(tile_count)

            tile_count += 1

    print(f"✅ Total tiles saved: {tile_count}")
    print(f"🧨 Damaged tiles found: {len(damaged_tiles)}")
    if damaged_tiles:
        print(f"🧾 Tile indices with damage: {damaged_tiles[:20]}{'...' if len(damaged_tiles) > 20 else ''}")

def zip_output_folder(folder_path, zip_path):
    print(f"📦 Zipping output to: {zip_path}")
    shutil.make_archive(zip_path.replace('.zip', ''), 'zip', folder_path)
    print("✅ Zipping complete.")

# STEP 6: Main function
def main():
    print("📦 Loading pre- and post-event imagery...")
    with rasterio.open(PRE_PATH) as pre, rasterio.open(POST_PATH) as post:
        pre_img = pre.read([1, 2, 3])
        post_img = post.read([1, 2, 3])

    img_6ch = np.vstack((normalize_img(pre_img), normalize_img(post_img)))
    print("→ 6-channel image shape:", img_6ch.shape)

    print("📐 Reprojecting and clipping building polygons...")
    polygons = load_reprojected_polygons(LABEL_PATH, PRE_PATH)

    print("🧱 Rasterizing mask...")
    mask = rasterize_collapse_mask(polygons, PRE_PATH)

    print("📤 Tiling and saving...")
    tile_and_save(img_6ch, mask, OUT_DIR)

    print("📁 Creating ZIP archive...")
    zip_output_folder(OUT_DIR, ZIP_PATH)

# 🚀 Run the script
main()